### PR TITLE
Add dbus system service

### PR DESCRIPTION
**Pull request by janbrummer**
In cases where we are switchting users which are not allowed or are using a non graphical shell dbus user session will not work. User session are bound to xauthority and display environment variables. In those cases fallback to a system session running as specified user (default=root).

Fixes: https://github.com/janbrummer/libproxy2/issues/79

### CODE REVIEW

**Comment by janbrummer** [comment]
@DimStar77 Please give it a try.

**Comment by DimStar77** [comment]
The firing off of proxyd on the system bus seems to work fine.

(unrelated to that, I've seen it loading sysconfig data in my gnome user session instead of my gnome config - next issue to be filed)

**Comment by DimStar77** [comment]
> The firing off of proxyd on the system bus seems to work fine.

I don't think we have any timeout in place yet to shut the daemon down again though

**Comment by janbrummer** [comment]
> > The firing off of proxyd on the system bus seems to work fine.
> 
> I don't think we have any timeout in place yet to shut the daemon down again though

Feel free to add a new ticket regarding the timeout. Not sure whether it really helps as cpu consumption in idle is 0 and memory footprint is low. But hey, we can discuss it tomorrow.

For this PR i think we need a new option to allow changing the system user for the d-bus service..

**Comment by janbrummer** [comment]
Added a new option `dbus-system-user` to specify the user which will be used on D-Bus system session (default=root).

**Pull request merged**
