### PR TITLE
Add samples

### PR DESCRIPTION
**Pull request by janbrummer**
Fixes: https://github.com/janbrummer/libproxy2/issues/33

### CODE REVIEW

**Comment by janbrummer** [comment]
@DimStar77 Please have a look at the samples. Currently I'm using libproxy as library file but Px as package name. Ok?

**Comment by mcatanzaro** [comment]
Would be even better to show how to do something with the result, but this looks fine.

**Comment by janbrummer** [comment]
> Would be even better to show how to do something with the result, but this looks fine.

Good point, will update them.

**Comment by DimStar77** [comment]
> @DimStar77 Please have a look at the samples. Currently I'm using libproxy as library file but Px as package name. Ok?

I'd say acceptable; from gi.repository import Libproxy would feel slightly more obvious

**Pull request merged**
